// Indonesian texts for the Accounting Core: statuses, journal types and API refusals.

type Tone = 'ok' | 'warn' | 'bad' | 'info' | 'neutral'

export const ACCOUNTING_STATUS: Record<string, [string, Tone]> = {
  SUBMITTED: ['Menunggu persetujuan', 'info'],
  APPROVED: ['Disetujui', 'info'],
  REJECTED: ['Ditolak', 'warn'],
  POSTED: ['Terposting', 'ok'],
  REVERSED: ['Dibalik', 'neutral'],
  FUTURE: ['Belum dibuka', 'neutral'],
  OPEN: ['Terbuka', 'ok'],
  SOFT_CLOSED: ['Ditutup sementara', 'warn'],
  CLOSED: ['Ditutup', 'neutral'],
  CONFIGURING: ['Sedang disiapkan', 'warn'],
  READY: ['Siap', 'ok'],
  LOCKED: ['Terkunci', 'info'],
  PUBLISHED: ['Terbit', 'ok'],
  ARCHIVED: ['Diarsipkan', 'neutral'],
  FAILED: ['Gagal', 'bad'],
}

export const journalTypeLabels: Record<string, string> = {
  MANUAL: 'Jurnal umum',
  OPENING: 'Saldo awal',
  REVERSAL: 'Jurnal pembalik',
  SYSTEM: 'Jurnal otomatis',
}

export const accountTypeLabels: Record<string, string> = {
  ASSET: 'Aset',
  LIABILITY: 'Kewajiban',
  EQUITY: 'Ekuitas',
  REVENUE: 'Pendapatan',
  EXPENSE: 'Beban',
}

export const frameworkLabels: Record<string, string> = {
  SAK_GENERAL: 'SAK Umum',
  SAK_EP: 'SAK EP',
  SAK_EMKM: 'SAK EMKM',
  CUSTOM: 'Kustom',
}

export const sideLabels: Record<string, string> = { DEBIT: 'Debit', CREDIT: 'Kredit' }

export const eventComponentLabels: Record<string, string> = { net: 'Nilai bersih', tax: 'Pajak', total: 'Total', amount: 'Jumlah' }

export const ACCOUNTING_ERRORS: Record<string, string> = {
  ACCOUNTING_NOT_CONFIGURED: 'Profil akuntansi belum disimpan.',
  ACCOUNTING_NOT_READY: 'Akuntansi belum diaktifkan. Selesaikan pengaturan awal terlebih dahulu.',
  ACCOUNTING_SETUP_INCOMPLETE: 'Masih ada langkah pengaturan wajib yang belum selesai.',
  ACCOUNTING_PROFILE_LOCKED: 'Mata uang fungsional dan presisi tidak dapat diubah setelah jurnal pertama diposting.',
  ACCOUNT_CODE_TAKEN: 'Kode akun sudah dipakai.',
  ACCOUNT_CONTROL_RESTRICTED: 'Akun kontrol hanya menerima posting dari sub-buku, bukan jurnal umum.',
  ACCOUNT_CURRENCY_MISMATCH: 'Akun ini dibatasi untuk mata uang lain.',
  ACCOUNT_CURRENCY_UNSUPPORTED: 'Mata uang akun harus sama dengan mata uang fungsional.',
  ACCOUNT_HAS_ACTIVE_CHILDREN: 'Nonaktifkan dulu akun turunannya.',
  ACCOUNT_HIERARCHY_CYCLE: 'Induk akun ini akan membentuk lingkaran.',
  ACCOUNT_HIERARCHY_INVALID: 'Induk harus akun induk (header) dengan tipe yang sama; akun induk tidak boleh menerima posting.',
  ACCOUNT_INACTIVE: 'Akun tidak aktif.',
  ACCOUNT_IN_USE: 'Akun sudah dipakai (riwayat jurnal, turunan, atau pemetaan). Nonaktifkan, jangan hapus; tipe dan saldo normal tidak dapat diubah.',
  ACCOUNT_MAPPED: 'Akun ini dipakai pemetaan peran. Ubah pemetaannya dulu.',
  ACCOUNT_MAPPING_CONFLICT: 'Peran ini sudah punya pemetaan untuk cakupan tersebut. Simpan ulang.',
  ACCOUNT_MAPPING_INVALID: 'Akun yang dipetakan sudah tidak aktif.',
  ACCOUNT_MAPPING_IN_USE: 'Aturan posting yang terbit memakai peran ini. Petakan ke akun lain, jangan dihapus.',
  ACCOUNT_MAPPING_MISSING: 'Ada peran akun yang belum dipetakan ke akun.',
  ACCOUNT_NOT_FOUND: 'Akun tidak ditemukan.',
  ACCOUNT_NOT_MAPPABLE: 'Hanya akun posting yang aktif yang dapat dipetakan.',
  ACCOUNT_NOT_POSTABLE: 'Akun induk (header) tidak dapat dipakai pada baris jurnal.',
  ACCOUNT_PARENT_INACTIVE: 'Aktifkan dulu akun induknya.',
  ACCOUNT_PARENT_NOT_FOUND: 'Akun induk tidak ditemukan.',
  ACCOUNT_ROLE_UNKNOWN: 'Peran akun tidak dikenal.',
  ACCOUNTING_EVENT_CONFLICT: 'Fakta bisnis ini sudah diposting dengan isi yang berbeda.',
  AMOUNT_INVALID: 'Jumlah harus berupa angka desimal tanpa tanda minus dan sesuai presisi mata uang.',
  LINE_AMOUNT_INVALID: 'Setiap baris harus berisi tepat satu sisi, debit atau kredit, dengan nilai lebih dari nol.',
  COA_NOT_EMPTY: 'Templat hanya dapat diterapkan pada bagan akun yang masih kosong.',
  COA_TEMPLATE_NOT_FOUND: 'Templat bagan akun tidak ditemukan.',
  COST_CENTER_CODE_TAKEN: 'Kode pusat biaya sudah dipakai.',
  DATA_SCOPE_DENIED: 'Anda hanya dapat membukukan ke cabang dan unit bisnis dalam cakupan data Anda.',
  DIMENSION_INACTIVE: 'Dimensi yang dipilih tidak aktif.',
  DIMENSION_INVALID: 'Dimensi tidak valid.',
  DIMENSION_MISMATCH: 'Unit bisnis tidak berada di cabang yang dipilih.',
  DIMENSION_NOT_FOUND: 'Cabang, unit bisnis, atau pusat biaya tidak ditemukan.',
  EVENT_COMPONENT_MISSING: 'Contoh data tidak memuat semua komponen yang dipakai aturan.',
  EVENT_EMPTY: 'Kejadian tidak menghasilkan baris jurnal.',
  EVENT_TYPE_UNKNOWN: 'Jenis kejadian akuntansi tidak dikenal.',
  EXPORT_TOO_LARGE: 'Data terlalu besar untuk diekspor. Persempit rentang tanggal atau akun.',
  FINANCIAL_INVARIANT_VIOLATION: 'Pembukuan ditolak oleh aturan integritas keuangan.',
  FISCAL_YEAR_CODE_TAKEN: 'Kode tahun fiskal atau periode sudah dipakai.',
  FISCAL_YEAR_HAS_OPEN_PERIODS: 'Tutup semua periode sebelum menutup tahun fiskal.',
  FISCAL_YEAR_INVALID_LENGTH: 'Tahun fiskal terdiri dari 1 sampai 18 periode bulanan.',
  FISCAL_YEAR_INVALID_START: 'Tahun fiskal dimulai pada tanggal 1 suatu bulan.',
  FISCAL_YEAR_NOT_DRAFT: 'Hanya tahun fiskal berstatus draf yang dapat dibuka atau dihapus.',
  FISCAL_YEAR_NOT_OPEN: 'Tahun fiskal untuk tanggal ini belum dibuka.',
  FISCAL_YEAR_OVERLAP: 'Tahun fiskal ini bertabrakan dengan tahun fiskal lain.',
  JOURNAL_ALREADY_POSTED: 'Jurnal ini sudah diposting.',
  JOURNAL_ALREADY_REVERSED: 'Jurnal ini sudah pernah dibalik.',
  JOURNAL_APPROVAL_REQUIRED: 'Kebijakan akuntansi mewajibkan persetujuan sebelum posting.',
  JOURNAL_DUPLICATE: 'Posting ini menduplikasi jurnal yang sudah ada.',
  JOURNAL_IMMUTABLE: 'Jurnal yang sudah diposting tidak dapat diubah. Gunakan jurnal pembalik.',
  JOURNAL_INVALID_TRANSITION: 'Perubahan status ini tidak diizinkan dari status jurnal saat ini.',
  JOURNAL_IS_REVERSAL: 'Jurnal pembalik tidak dapat dibalik lagi; buat jurnal koreksi.',
  JOURNAL_NOT_DRAFT: 'Hanya jurnal berstatus draf yang dapat diubah.',
  JOURNAL_NOT_MANUAL: 'Hanya jurnal umum yang memakai alur ini. Saldo awal dikelola di halamannya sendiri.',
  JOURNAL_NOT_OPENING: 'Bukan jurnal saldo awal.',
  JOURNAL_NOT_POSTABLE: 'Jurnal pada status ini tidak dapat diposting.',
  JOURNAL_NOT_POSTED: 'Hanya jurnal yang sudah diposting yang dapat dibalik.',
  JOURNAL_TOO_FEW_LINES: 'Jurnal membutuhkan minimal dua baris.',
  JOURNAL_UNBALANCED: 'Jurnal tidak seimbang: total debit harus sama dengan total kredit.',
  OPENING_BALANCE_HISTORY_EXISTS: 'Sudah ada jurnal terposting sebelum tanggal cutover. Pilih tanggal cutover pada atau sebelum jurnal pertama.',
  OPENING_BALANCE_NOT_FOUND: 'Saldo awal tidak ditemukan.',
  OPENING_BALANCE_POSTED: 'Saldo awal sudah diposting. Balik jurnalnya untuk memulai ulang.',
  PERIOD_CLOSED: 'Periode akuntansi sudah ditutup.',
  PERIOD_HAS_PENDING_JOURNALS: 'Masih ada jurnal yang menunggu persetujuan atau posting pada periode ini.',
  PERIOD_INVALID_TRANSITION: 'Perubahan status periode ini tidak diizinkan.',
  PERIOD_NOT_FOUND: 'Tidak ada periode akuntansi untuk tanggal ini.',
  PERIOD_NOT_OPEN: 'Periode akuntansi belum dibuka.',
  PERIOD_SOFT_CLOSED: 'Periode ditutup sementara. Hanya pengguna dengan izin khusus yang dapat memposting.',
  POSTING_BEFORE_CUTOVER: 'Tanggal posting sebelum tanggal cutover saldo awal.',
  POSTING_RULE_CODE_TAKEN: 'Kode aturan posting sudah dipakai. Buat versi baru dari aturan tersebut.',
  POSTING_RULE_COMPONENT_INVALID: 'Baris aturan memakai komponen yang tidak dimiliki jenis kejadian ini.',
  POSTING_RULE_DRAFT_EXISTS: 'Aturan ini sudah memiliki versi draf.',
  POSTING_RULE_IMMUTABLE: 'Aturan posting yang sudah terbit tidak dapat diubah. Buat versi baru.',
  POSTING_RULE_INCOMPLETE: 'Aturan posting membutuhkan minimal satu baris debit dan satu baris kredit.',
  POSTING_RULE_IS_DRAFT: 'Versi ini masih draf; ubah langsung.',
  POSTING_RULE_NOT_FOUND: 'Tidak ada aturan posting yang berlaku untuk jenis kejadian dan tanggal ini.',
  POSTING_RULE_NOT_PUBLISHED: 'Hanya aturan yang terbit yang dapat diarsipkan.',
  POSTING_RULE_WINDOW_INVALID: 'Tanggal berakhir tidak boleh sebelum aturan mulai berlaku.',
  POSTING_RULE_WINDOW_OVERLAP: 'Versi lain dari jenis kejadian ini sudah berlaku pada tanggal tersebut.',
  RANGE_INVALID: 'Tanggal mulai tidak boleh setelah tanggal akhir.',
  REVERSAL_DATE_INVALID: 'Tanggal pembalikan tidak boleh sebelum jurnal yang dibalik.',
  SOD_VIOLATION: 'Pemisahan tugas: Anda tidak dapat melakukan langkah ini pada jurnal yang Anda siapkan atau setujui sendiri.',
}
