// Indonesian texts for the OA2 modules (payables, expense, cash & bank): statuses, option labels and API refusals.

type Tone = 'ok' | 'warn' | 'bad' | 'info' | 'neutral'

export const OPERATIONAL_STATUS: Record<string, [string, Tone]> = {
  UNPAID: ['Belum dibayar', 'warn'],
  PARTIALLY_PAID: ['Dibayar sebagian', 'info'],
  PAID: ['Lunas', 'ok'],
  MATCHED: ['Cocok', 'ok'],
  UNMATCHED: ['Belum dicocokkan', 'warn'],
  EXCEPTION: ['Pengecualian', 'info'],
  MISMATCH: ['Selisih', 'bad'],
  IN_PROGRESS: ['Sedang berjalan', 'info'],
  RECONCILED: ['Terekonsiliasi', 'ok'],
  DIFFERENCE: ['Ada selisih', 'bad'],
  COMPLETED: ['Selesai', 'ok'],
}

export const operationalModuleLabels: Record<string, string> = {
  ACCOUNTING_CORE: 'Inti akuntansi',
  ACCOUNTING_AP: 'Utang usaha',
  ACCOUNTING_EXPENSE: 'Beban',
  ACCOUNTING_CASH_BANK: 'Kas & bank',
}

export const paymentMethodLabels: Record<string, string> = { TRANSFER: 'Transfer bank', CASH: 'Tunai', CHEQUE: 'Cek', GIRO: 'Giro', OTHER: 'Lainnya' }
export const termTypeLabels: Record<string, string> = { NET_DAYS: 'Neto (hari)', END_OF_MONTH: 'Akhir bulan', CUSTOM: 'Tanggal ditentukan sendiri', IMMEDIATE: 'Segera' }
export const settlementLabels: Record<string, string> = { PAYABLE: 'Dicatat sebagai utang', DIRECT_PAID: 'Dibayar langsung' }
export const cashKindLabels: Record<string, string> = { CASH: 'Kas', BANK: 'Bank' }
export const invoiceOriginLabels: Record<string, string> = { INVOICE: 'Faktur vendor', EXPENSE: 'Dari beban' }
export const directionLabels: Record<string, string> = { IN: 'Masuk', OUT: 'Keluar' }

export const OPERATIONAL_ERRORS: Record<string, string> = {
  ACCOUNT_NOT_CONTROL: 'Akun ini bukan akun kontrol.',
  ACCOUNT_ROLE_INVALID: 'Peran akun ini tidak dapat dipakai untuk klasifikasi.',
  ACCOUNT_ROLE_DOCUMENT_BOUND: 'Peran ini mengambil akunnya dari dokumen sumber; tidak ada pemetaan tenant.',
  AGING_BUCKETS_INVALID: 'Kelompok umur utang adalah 1 sampai 8 batas hari yang menaik, antara 1 dan 3650.',
  AP_ALLOCATION_DUPLICATE: 'Satu faktur hanya dapat dialokasikan sekali per pembayaran.',
  AP_ALLOCATION_EXCEEDS_OUTSTANDING: 'Alokasi melebihi saldo faktur yang masih terutang.',
  AP_ALLOCATION_EXCEEDS_PAYMENT: 'Jumlah alokasi melebihi jumlah pembayaran.',
  AP_ALLOCATION_INVALID: 'Setiap alokasi harus lebih besar dari nol.',
  AP_ALLOCATION_VENDOR_MISMATCH: 'Pembayaran hanya dapat melunasi faktur milik vendor yang sama.',
  AP_INVOICE_DISCOUNT_INVALID: 'Diskon tidak boleh melebihi subtotal.',
  AP_INVOICE_DUPLICATE: 'Vendor ini sudah memiliki faktur dengan nomor tersebut.',
  AP_INVOICE_HAS_PAYMENTS: 'Faktur sudah dialokasikan ke pembayaran. Balik pembayarannya terlebih dahulu.',
  AP_INVOICE_NOT_FOUND: 'Faktur tidak ditemukan.',
  AP_INVOICE_NOT_PAYABLE: 'Hanya faktur yang sudah diposting yang dapat dilunasi.',
  AP_INVOICE_NOT_POSTABLE: 'Utang yang berasal dari beban diposting bersama bebannya.',
  AP_INVOICE_NOT_REVERSIBLE: 'Utang yang berasal dari beban dibalik bersama bebannya.',
  AP_INVOICE_NO_LINES: 'Faktur memerlukan sedikitnya satu baris.',
  AP_INVOICE_NUMBER_REQUIRED: 'Nomor faktur vendor wajib diisi.',
  AP_INVOICE_TOO_MANY_LINES: 'Satu faktur paling banyak 300 baris.',
  AP_INVOICE_TOTAL_INVALID: 'Total faktur harus lebih besar dari nol.',
  AP_PAYMENT_BEFORE_INVOICE: 'Pembayaran tidak dapat diposting sebelum tanggal faktur yang dilunasinya.',
  AP_POSTING_RULE_INVALID: 'Aturan posting untuk peristiwa ini harus memakai peran utang usaha dan kas/bank sesuai ketentuan.',
  BANK_BOOK_LINE_ALREADY_MATCHED: 'Baris buku ini sudah dicocokkan dengan baris rekening koran lain.',
  BANK_BOOK_LINE_NOT_FOUND: 'Itu bukan baris yang sudah diposting pada akun bank ini.',
  BANK_EXCEPTION_REASON_REQUIRED: 'Tuliskan alasan baris ini menjadi pengecualian.',
  BANK_ITEM_AMOUNT_INVALID: 'Baris rekening koran memerlukan jumlah bukan nol (setoran positif, penarikan negatif).',
  BANK_ITEM_INVALID: 'Setiap baris rekening koran memerlukan tanggal dan keterangan.',
  BANK_ITEM_MATCHED: 'Lepas pencocokan baris ini terlebih dahulu.',
  BANK_ITEM_TOO_MANY: 'Satu permintaan paling banyak 1000 baris rekening koran.',
  BANK_MATCH_AMOUNT_MISMATCH: 'Baris rekening koran dan baris buku harus berjumlah sama dan searah.',
  BANK_NAME_REQUIRED: 'Akun bank memerlukan nama bank.',
  BANK_STATEMENT_COMPLETED: 'Rekonsiliasi bank yang sudah selesai tidak dapat diubah.',
  BANK_STATEMENT_HAS_MATCHES: 'Lepas pencocokan semua baris sebelum menghapus rekening koran.',
  BANK_STATEMENT_HAS_UNMATCHED_ITEMS: 'Cocokkan setiap baris rekening koran atau tandai sebagai pengecualian sebelum menyelesaikan rekonsiliasi.',
  BANK_STATEMENT_INVALID: 'Data rekening koran belum lengkap atau tidak valid.',
  BANK_STATEMENT_NOT_BANK_ACCOUNT: 'Rekening koran milik akun bank, bukan kas.',
  BANK_STATEMENT_REFERENCE_TAKEN: 'Akun bank ini sudah memiliki rekening koran dengan referensi tersebut.',
  CASH_ACCOUNT_HAS_NO_BANK_DATA: 'Akun kas tidak memiliki data bank.',
  CASH_BANK_ACCOUNT_INACTIVE: 'Akun kas/bank ini tidak aktif.',
  CASH_BANK_ACCOUNT_IN_USE: 'Akun ini sudah memiliki dokumen: nonaktifkan, jangan hapus. Akun buku besar, mata uang, dan jenisnya tidak dapat diubah lagi.',
  CASH_BANK_ACCOUNT_NOT_FOUND: 'Akun kas/bank tidak ditemukan.',
  CASH_BANK_ACCOUNT_REQUIRED: 'Akun kas/bank wajib diisi.',
  CASH_BANK_KIND_INVALID: 'Jenis harus Kas atau Bank.',
  CASH_POSTING_RULE_INVALID: 'Aturan posting kas/bank harus memindahkan jumlah antara peran kas/bank dan peran akun dokumen.',
  CASH_TRANSACTION_AMOUNT_INVALID: 'Jumlah harus lebih besar dari nol.',
  CASH_TRANSACTION_COUNTER_IS_CASH_BANK: 'Akun lawan tidak boleh akun kas/bank; perpindahan antar kas/bank belum didukung.',
  CASH_TRANSACTION_KIND_INVALID: 'Jenis transaksi kas tidak dikenal.',
  CASH_TRANSACTION_PURPOSE_REQUIRED: 'Tuliskan tujuan transaksi.',
  COUNTER_ACCOUNT_REQUIRED: 'Akun lawan wajib diisi.',
  CURRENCY_NOT_SUPPORTED: 'Modul ini hanya mencatat dalam mata uang fungsional.',
  DESCRIPTION_REQUIRED: 'Deskripsi wajib diisi.',
  DOCUMENT_ALREADY_POSTED: 'Dokumen ini sudah diposting.',
  DOCUMENT_APPROVAL_REQUIRED: 'Dokumen ini harus disetujui sebelum diposting.',
  DOCUMENT_DATE_REQUIRED: 'Tanggal dokumen wajib diisi.',
  DOCUMENT_IMMUTABLE: 'Dokumen yang sudah diposting tidak dapat diubah. Koreksi dengan pembalikan.',
  DOCUMENT_INVALID_TRANSITION: 'Perubahan status ini tidak diizinkan dari status dokumen saat ini.',
  DOCUMENT_NOT_DRAFT: 'Dokumen hanya dapat diubah selama masih berstatus draf.',
  DOCUMENT_NOT_POSTABLE: 'Dokumen ini belum dapat diposting.',
  DUE_DATE_INVALID: 'Jatuh tempo tidak boleh sebelum tanggal dokumen.',
  DUE_DATE_OVERRIDE_NOT_ALLOWED: 'Termin pembayaran ini tidak mengizinkan jatuh tempo yang berbeda.',
  DUE_DATE_REQUIRED: 'Termin pembayaran ini memerlukan tanggal jatuh tempo yang diisi sendiri.',
  DUPLICATE_OVERRIDE_NOT_ALLOWED: 'Anda tidak diizinkan mencatat nomor faktur vendor yang sama.',
  DUPLICATE_OVERRIDE_REASON_REQUIRED: 'Tuliskan alasan mencatat nomor faktur vendor yang sama.',
  EXPENSE_AMOUNT_INVALID: 'Jumlah beban harus lebih besar dari nol.',
  EXPENSE_CATEGORY_CODE_TAKEN: 'Kategori beban dengan kode ini sudah ada.',
  EXPENSE_CATEGORY_DESTINATION_AMBIGUOUS: 'Kategori memilih akun atau peran, bukan keduanya.',
  EXPENSE_CATEGORY_INACTIVE: 'Kategori beban ini tidak aktif.',
  EXPENSE_CATEGORY_INVALID: 'Kategori beban tidak valid atau tidak ditemukan.',
  EXPENSE_CATEGORY_IN_USE: 'Kategori ini dipakai beban atau baris faktur: nonaktifkan, jangan hapus.',
  EXPENSE_DATE_REQUIRED: 'Tanggal beban wajib diisi.',
  EXPENSE_HAS_PAYMENTS: 'Utang dari beban ini sudah dilunasi sebagian atau seluruhnya. Balik pembayarannya terlebih dahulu.',
  EXPENSE_POSTING_RULE_INVALID: 'Aturan posting beban harus sesuai ketentuan peran akun.',
  EXPENSE_SETTLEMENT_INVALID: 'Pilih cara penyelesaian beban: utang atau dibayar langsung.',
  FISCAL_YEAR_MISSING: 'Buat tahun fiskal sebelum menerapkan aturan posting standar.',
  LINE_DESCRIPTION_REQUIRED: 'Setiap baris memerlukan deskripsi.',
  LINE_QUANTITY_INVALID: 'Kuantitas dan harga satuan harus diisi bersama, dan kuantitas harus lebih besar dari nol.',
  PAYMENT_AMOUNT_INVALID: 'Jumlah pembayaran harus lebih besar dari nol.',
  PAYMENT_DATE_REQUIRED: 'Tanggal pembayaran wajib diisi.',
  PAYMENT_METHOD_INVALID: 'Metode pembayaran tidak dikenal.',
  PAYMENT_NOT_FULLY_ALLOCATED: 'Pembayaran harus dialokasikan penuh ke faktur vendor sebelum disetujui atau diposting.',
  PAYMENT_TERM_CODE_TAKEN: 'Termin pembayaran dengan kode ini sudah ada.',
  PAYMENT_TERM_DAYS_INVALID: 'Jumlah hari jatuh tempo harus antara 0 dan 3650.',
  PAYMENT_TERM_INACTIVE: 'Termin pembayaran ini tidak aktif.',
  PAYMENT_TERM_IN_USE: 'Termin ini dipakai vendor atau faktur: nonaktifkan, jangan hapus.',
  PAYMENT_TERM_NOT_FOUND: 'Termin pembayaran tidak ditemukan.',
  PAYMENT_TERM_TYPE_INVALID: 'Jenis termin pembayaran tidak dikenal.',
  TRANSACTION_DATE_REQUIRED: 'Tanggal transaksi wajib diisi.',
  VENDOR_EXTERNAL_REFERENCE_INVALID: 'Referensi eksternal memerlukan sistem sumber dan id sekaligus.',
  VENDOR_INACTIVE: 'Vendor ini tidak aktif.',
  VENDOR_IN_USE: 'Vendor ini sudah memiliki dokumen: nonaktifkan, jangan hapus.',
  VENDOR_NOT_FOUND: 'Vendor tidak ditemukan.',
  VENDOR_REQUIRED: 'Vendor wajib diisi.',
  POSTING_RULE_ROLE_RESTRICTED: 'Peran utang usaha hanya boleh dipakai aturan posting untuk peristiwa utang usaha.',
  EXPORT_TOO_LARGE: 'Ekspor terlalu besar. Persempit filter lalu coba lagi.',
}
